<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>AI_ChatBox</RootNamespace>
    <UserSecretsId>a4fa596f-3633-4020-a055-fe353949f275</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenAI" Version="2.13.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

</Project>
